# -----------------------
# 网站基本信息
# -----------------------
title: 袁乃康的技术文档
description: 这是一个示例文档
url: "https://naikangyuan.github.io"

# -----------------------
# 关键路径设置
# -----------------------
baseurl: "/Yuan_ASPECT_tutorial"

# -----------------------
# 换成新的主题 (Just the Docs)
# -----------------------
remote_theme: pmarsceill/just-the-docs

# -----------------------
# 开启搜索功能
# -----------------------
search_enabled: true

# -----------------------
# 辅助链接 (显示在右上角，可选)
# -----------------------
aux_links:
  "GitHub 仓库":
    - "https://github.com/naikangyuan/Yuan_ASPECT_tutorial"
footer_content: "Copyright &copy; 2026 Naikangyuan. All rights reserved."

# 颜色设置 (可选)
color_scheme: light
