# -----------------------
# 网站基本信息
# -----------------------
title: 我的技术文档
description: 这是一个示例文档
url: "https://naikangyuan.github.io"

# -----------------------
# 关键路径设置 (这里改了！)
# -----------------------
# 必须加上斜杠 "/"
baseurl: "/Yuan_ASPECT_tutorial"

# -----------------------
# 主题设置
# -----------------------
remote_theme: rundocs/jekyll-rtd-theme@2.0.10

# -----------------------
# 插件
# -----------------------
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# -----------------------
# 排除文件
# -----------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
